In [1]:
from joblib import dump,load
import numpy as np
model = load('Dragon.joblib')

In [2]:
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24018342, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([22.437])

In [3]:
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.74018342, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([21.193])

In [4]:
features = np.array([[-0.93942006,  4.12928155, -9.12165014, -0.27288841, -1.42262747,
       -0.94018342, -99.31238772,  6.61111401, -7.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.96091034]])
model.predict(features)

array([21.68])

## using the model

In [5]:
from joblib import dump,load
import numpy as np
model = load('Dragon.joblib')
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24018342, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([22.437])